application:
  appId: sig-pet-clinic
  assetId: sig-pet-clinic
  projectLanguage: Java
  platformVersion: Java 10
  buildSystem: Maven
  riskMatrixRevision: employeeApps-1.0
  sourceFilePattern: ".*\\+\\+\\+.*(\\.java)+.*"
  sensitivePackagePattern: "password"
  fileChangeThreshold: 5

environment:
  enableJira: false
  enableScm: false
  scmOwner: "xenserverarmy"
  scmRepositoryName: "spring-framework-petclinic"
  scmBranchName: "master"
  githubApiUrl: "https://api.github.com/repos/"
